<!DOCTYPE html>
<html>
<head>
    <title>Your Autogenerated Password</title>
</head>
<body>
    <h1>Hello!</h1>
    <p>Your autogenerated password is: <strong>{{ $password }}</strong></p>
    <p>Please keep this password secure.</p>
</body>
</html>
